import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { exec } from "node:child_process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const pluginId = "agent-client";

// Plugin to reload Obsidian plugin after build (dev mode only)
const reloadPlugin = {
	name: "reload-plugin",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				exec(`obsidian plugin:reload ${pluginId}`, (error, stdout, stderr) => {
					if (error) {
						// Silently ignore if obsidian CLI is not available
						if (!error.message.includes("command not found")) {
							console.log(`[reload] ${error.message}`);
						}
						return;
					}
					if (stdout) console.log(`[reload] ${stdout.trim()}`);
				});
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: prod ? [] : [reloadPlugin],
});

if (prod) {
	await context.rebuild();
	// Also reload in production build for development convenience
	exec(`obsidian plugin:reload ${pluginId}`, (error, stdout, stderr) => {
		if (error) {
			if (!error.message.includes("command not found")) {
				console.log(`[reload] ${error.message}`);
			}
		} else if (stdout) {
			console.log(`[reload] ${stdout.trim()}`);
		}
	});
	process.exit(0);
} else {
	await context.watch();
}
